version: "3"

services:
  db1:
    image: mariadb:10.6
    container_name: mariadb-node1
    hostname: db1
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=rullabcd
      - MYSQL_PASSWORD=siswa123
    volumes:
      - ./galera/node1.cnf:/etc/mysql/conf.d/galera.cnf
      - db1-data:/var/lib/mysql
    command: --wsrep-new-cluster
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db2:
    image: mariadb:10.6
    container_name: mariadb-node2
    hostname: db2
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
    volumes:
      - ./galera/node2.cnf:/etc/mysql/conf.d/galera.cnf
      - db2-data:/var/lib/mysql
    depends_on:
      db1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db3:
    image: mariadb:10.6
    container_name: mariadb-node3
    hostname: db3
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
    volumes:
      - ./galera/node3.cnf:/etc/mysql/conf.d/galera.cnf
      - db3-data:/var/lib/mysql
    depends_on:
      db2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    hostname: proxysql
    networks:
      - galera-net
    ports:
      - "6032:6032" # Admin Port
      - "6033:6033" # SQL Port
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
      - ./proxysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - proxysql-data:/var/lib/proxysql
    depends_on:
      db3:
        condition: service_healthy

networks:
  galera-net:
    driver: bridge

volumes:
  db1-data:
  db2-data:
  db3-data:
  proxysql-data:
